---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - epel-release 
        - htop
        - tmux
        - vim
        - python3-psutil

  - name: copy wallpaper file
    copy:
      src: files/AlmaLinux.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

